server:
  mode: 0 # Modes: 0: normal  1: testing
  host: "0.0.0.0"
  port: "5000"
  debug: yes
  static-directory: "public"

globals:
  s:
    value:
      value: "abc"
      type: "string"
    value2:
      value: "abc2"
      type: "string"
